name = "realtime-worker"
main = "src/index.ts"
compatibility_date = "2024-12-01"

[durable_objects]
bindings = [
  { name = "RETRO_ROOM", class_name = "RetroRoom" },
  { name = "CRAPS_ROOM", class_name = "CrapsRoom" }
]

[[migrations]]
tag = "v1"
new_sqlite_classes = ["RetroRoom"]

[[migrations]]
tag = "v2"
new_sqlite_classes = ["CrapsRoom"]
